[profile.default]
archive.include = [
    { path = "debug/golem", relative-to = "target" },
    { path = "debug/golem-component-compilation-service", relative-to = "target" },
    { path = "debug/golem-shard-manager", relative-to = "target" },
]
